
# Path to the PNPRO template you want to repair/generate
pnpro_path: "net/hypernode_minimal_doublet.PNPRO"

# Which extracellular metabolites to project onto all FBA models
metabolite_places:
  - "glc__D_e"
  - "lcts_e"

# The list of organisms in your community
organisms:
  - model_name: "Escherichia_coli_SE11"
    organism_label: "Escherichia coli SE11"
    abbreviation:   "ecs"           # pick from derive_abbrs()
    txt_file:       "Escherichia_coli_SE11"
    # biomass parameters: max, mean, min
    biomass:
      max:  1.172
      mean: 0.489
      min:  0.083
    # population kinetics: starvation, duplication, death rates
    population:
      starv: 0.21
      dup:   1.00
      death: 0.018
    initial_count: 1e6

  - model_name: "Clostridium_butyricum_DSM_10702"
    organism_label: "Clostridium butyricum DSM 10702"
    abbreviation:   "cbd1"          # pick from derive_abbrs()
    txt_file:       "Clostridium_butyricum_DSM_10702"
    biomass:
      max:  1.500
      mean: 0.600
      min:  0.100
    population:
      starv: 0.21
      dup:   1.00
      death: 0.018
    initial_count: 1e6

