# config/models.yaml

boundary_metabolites:

cellular_units:
  - model_name: "Escherichia_coli_str_K_12_substr_MG1655"
    label:      "Escherichia coli str K 12 substr MG1655"
    biomass:
      max:  1.172
      mean: 0.489
      min:  0.083
    population:
      starv: 0.21
      dup:   1.00
      death: 0.018
    initial_count: 1e+03

